title = "Comment pouvons-nous vous aider ?"

[[choices]]
label = "💁🏻‍♀️ J'ai une question"
id = "help"

  [choices.link]
  title = "Votre question porte sur ?"

    [[choices.link.choices]]
    label = "Des données en particulier"
    id = "dataset"

      [choices.link.choices.link]
      title = "Sur quelles données avez vous des questions ?"

        [[choices.link.choices.link.choices]]
        label = "Associations (RNA)"
        id = "rna"

          [choices.link.choices.link.choices.link]
          path = "answers/numero_rna.md"

        [[choices.link.choices.link.choices]]
        label = "Personnes décédées"
        id = "deces"

          [choices.link.choices.link.choices.link]
          path = "answers/deces.md"

        [[choices.link.choices.link.choices]]
        label = "Formation"
        id = "formation"

          [choices.link.choices.link.choices.link]
          path = "answers/formation.md"

        [[choices.link.choices.link.choices]]
        label = "SIREN & SIRET"
        id = "siret"

          [choices.link.choices.link.choices.link]
          path = "answers/siret.md"

        [[choices.link.choices.link.choices]]
        label = "Immobilier (DVF)"
        id = "dvf"

          [choices.link.choices.link.choices.link]
          path = "answers/dvf.md"

        [[choices.link.choices.link.choices]]
        label = "Base Adresse Nationale (BAN)"
        id = "ban"

          [choices.link.choices.link.choices.link]
          path = "answers/ban.md"

        [[choices.link.choices.link.choices]]
        label = "API découpage administratif"
        id = "decoupage"

          [choices.link.choices.link.choices.link]
          path = "answers/decoupe.md"

        [[choices.link.choices.link.choices]]
        label = "IRVE"
        id = "irve"

          [choices.link.choices.link.choices.link]
          path = "answers/irve.md"

        [[choices.link.choices.link.choices]]
        label = "Données géographiques"
        id = "geo"

          [choices.link.choices.link.choices.link.form]
          title = "Que souhaitez-vous nous dire ?"
          recipient = "geo@data.gouv.fr"

        [[choices.link.choices.link.choices]]
        label = "Autre"
        id = "other"

          [choices.link.choices.link.choices.link]
          path = "answers/question_donnees.md"

    [[choices.link.choices]]
    label = "Une API"
    id = "api"

      [choices.link.choices.link]
      title = "Comment pouvons-nous vous aider ?"

        [[choices.link.choices.link.choices]]
        label = "Demande d'information sur une API spécifique"
        id = "apispecifique"

          [choices.link.choices.link.choices.link]
          path = "answers/api_api-specifique.md"

        [[choices.link.choices.link.choices]]
        label = "API non-référencée dans le catalogue"
        id = "apinonreferencee"

          [choices.link.choices.link.choices.link]
          path = "answers/api_recherche-api-non-referencee.md"

        [[choices.link.choices.link.choices]]
        label = "Référencer une API"
        id = "referencerapi"

          [choices.link.choices.link.choices.link]
          path = "answers/api_referencer-api.md"

        [[choices.link.choices.link.choices]]
        label = "API en accès restreint"
        id = "apiaccesrestreint"

          [choices.link.choices.link.choices.link]
          path = "answers/api_api-acces-restreint.md"

        [[choices.link.choices.link.choices]]
        label = "Autre"
        id = "apiother"

          [choices.link.choices.link.choices.link]
          path = "answers/api_other.md"

    [[choices.link.choices]]
    label = "Une procédure administrative"
    id = "admin"

      [choices.link.choices.link]
      path = "answers/demarches_admin.md"

    [[choices.link.choices]]
    label = "L'utilisation de data.gouv.fr"
    id = "datagouv"

      [choices.link.choices.link]
      title = "Comment pouvons-nous vous aider ?"

        [[choices.link.choices.link.choices]]
        label = "Faire certifier son organisation"
        id = "certification"

          [choices.link.choices.link.choices.link.form]
          title = "Pensez à nous envoyer un lien vers votre organisation ?"
          recipient = "certification@data.gouv.fr"

        [[choices.link.choices.link.choices]]
        label = "Référencer ou moissonner ses données sur data.gouv.fr"
        id = "moissonnage"

          [choices.link.choices.link.choices.link.form]
          title = "Que souhaitez-vous nous dire ?"
          recipient = "moissonnage@data.gouv.fr"

        [[choices.link.choices.link.choices]]
        label = "Autre"
        id = "autre"

          [choices.link.choices.link.choices.link.form]
          title = "Que souhaitez-vous nous dire ?"
          recipient = "support@data.gouv.fr"

[[choices]]
label = "💡 Demande de données"
id = "opendata"

  [choices.link]
  path = "answers/demande_donnees.md"

[[choices]]
label = "🐛 Soumettre un bug"
id = "bug"

  [choices.link.form]
  title = "Quel problème rencontrez-vous ?"
  recipient = "support@data.gouv.fr"

[[choices]]
label = "💬 Faire un retour sur data.gouv.fr"
id = "feedback"

  [choices.link.form]
  title = "Que souhaitez-vous nous dire ?"
  recipient = "support@data.gouv.fr"
