title = "Comment pouvons-nous vous aider ?"
id = 'how-to-help'

[[choices]]
label = "💁🏻‍♀️ J'ai une question"
id = "help"
title = "Votre question porte sur ?"

  [[choices.choices]]
  label = "Des données en particulier"
  id = "dataset"
  title = "Sur quelles données avez vous des questions ?"
    [[choices.choices.choices]]
    label = "Associations (RNA)"
    id = "rna"
    answer = "numero_rna"

    [[choices.choices.choices]]
    label = "Personnes décédées"
    id = "deces"
    answer = "deces"

    [[choices.choices.choices]]
    label = "Formation"
    id = "formation"
    answer = "formation"

    [[choices.choices.choices]]
    label = "SIREN & SIRET"
    id = "siret"
    answer = "siret"

    [[choices.choices.choices]]
    label = "Immobilier (DVF)"
    id = "dvf"
    answer = "dvf"

    [[choices.choices.choices]]
    label = "Base Adresse Nationale (BAN)"
    id = "ban"
    answer = "ban"

    [[choices.choices.choices]]
    label = "API découpage administratif"
    id = "decoupage"
    answer = "decoupe"  

    [[choices.choices.choices]]
    label = "IRVE"
    id = "irve"
    answer = "irve"
      
    [[choices.choices.choices]]
    label = "Données géographiques"
    id = "geo"
    title = "Que souhaitez-vous nous dire ?"
    recipient = "geo@data.gouv.fr"
      
    [[choices.choices.choices]]
    label = "Autre"
    id = "other"
    answer = "question_donnees"

  [[choices.choices]]
  label = "Une API"
  id = "api"
  title = "Comment pouvons-nous vous aider ?"
    [[choices.choices.choices]]
    label = "Demande d'information sur une API spécifique"
    id = "apispecifique"
    answer = "api_api-specifique"

    [[choices.choices.choices]]
    label = "API non-référencée dans le catalogue"
    id = "apinonreferencee"
    answer = "api_recherche-api-non-referencee"

    [[choices.choices.choices]]
    label = "Référencer une API"
    id = "referencerapi"
    answer = "api_referencer-api"

    [[choices.choices.choices]]
    label = "API en accès restreint"
    id = "apiaccesrestreint"
    answer = "api_api-acces-restreint"

    [[choices.choices.choices]]
    label = "Autre"
    id = "apiother"
    answer = "api_other"

  [[choices.choices]]
  label = "Une procédure administrative"
  id = "admin"
  answer = "demarches_admin"

  [[choices.choices]]
    label = "L'utilisation de data.gouv.fr"
    id = "datagouv"
    title = "Comment pouvons-nous vous aider ?"
      [[choices.choices.choices]]
      label = "Faire certifier son organisation"
      id = "certification"
      title = "Pensez à nous envoyer un lien vers votre organisation ?"
      recipient = "certification@data.gouv.fr"

      [[choices.choices.choices]]
      label = "Référencer ou moissonner ses données sur data.gouv.fr"
      id = "moissonnage"
      title = "Que souhaitez-vous nous dire ?"
      recipient = "moissonnage@data.gouv.fr"

      [[choices.choices.choices]]
      label = "Autre"
      id = "autre"
      title = "Que souhaitez-vous nous dire ?"
      recipient = "support@data.gouv.fr"  

[[choices]]
label = "💡 Demande de données"
id = "opendata"
answer = "demande_donnees"
button_link = 'https://forum.data.gouv.fr/c/recherche-et-ouverture-de-donnees/8'
button_text = 'Consulter le forum'

[[choices]]
label = "🐛 Soumettre un bug"
id = "bug"
title = "Quel problème rencontrez-vous ?"
recipient = "support@data.gouv.fr"

[[choices]]
label = "💬 Faire un retour sur data.gouv.fr"
id = "feedback"
title = "Que souhaitez-vous nous dire ?"
recipient = "support@data.gouv.fr"
